import type { Token } from "./store";

// Deterministic mock data for marketplace UI
// Will be replaced with real Nostr data later

const NOW = Math.floor(Date.now() / 1000);

export const MOCK_TOKENS: (Token & {
  price: number;
  change24h: number;
  volume24h: number;
  holders: number;
  curveProgress: number;
  creatorShort: string;
})[] = [
  {
    id: "mock-1",
    name: "ArkFrog",
    ticker: "FROG",
    description: "The OG frog of the Ark network. First memecoin on vtxo.fun. Ribbit ribbit.",
    image: "",
    creator: "npub1qqqsyqcyqg9qvjz6t7dv2x6p0hw6s2x3s4a9k8f",
    createdAt: NOW - 180,
    marketCap: 284_500,
    supply: 1_000_000,
    replies: 47,
    price: 0.42,
    change24h: 124.5,
    volume24h: 89_200,
    holders: 312,
    curveProgress: 68,
    creatorShort: "5FaK...x9nQ",
  },
  {
    id: "mock-2",
    name: "Satoshi's Cat",
    ticker: "SCAT",
    description: "Satoshi had a cat. We found it. Now it lives on Ark.",
    image: "",
    creator: "npub1abcde12345",
    createdAt: NOW - 420,
    marketCap: 192_000,
    supply: 1_000_000,
    replies: 33,
    price: 0.28,
    change24h: 45.2,
    volume24h: 54_100,
    holders: 189,
    curveProgress: 52,
    creatorShort: "7BcD...m3Rp",
  },
  {
    id: "mock-3",
    name: "VTXO Maxi",
    ticker: "VMAX",
    description: "For the true believers. Stack VTXOs, not shitcoins. Well... except this one.",
    image: "",
    creator: "npub1xyz789",
    createdAt: NOW - 35,
    marketCap: 42_800,
    supply: 1_000_000,
    replies: 12,
    price: 0.06,
    change24h: 890.0,
    volume24h: 38_400,
    holders: 67,
    curveProgress: 14,
    creatorShort: "9XyZ...kL4v",
  },
  {
    id: "mock-4",
    name: "Lightning Pepe",
    ticker: "LPEPE",
    description: "Pepe but faster. Zaps only. No slow chains allowed.",
    image: "",
    creator: "npub1lnpepe",
    createdAt: NOW - 1200,
    marketCap: 521_000,
    supply: 1_000_000,
    replies: 89,
    price: 0.71,
    change24h: -8.3,
    volume24h: 124_800,
    holders: 534,
    curveProgress: 82,
    creatorShort: "2LnP...eP3z",
  },
  {
    id: "mock-5",
    name: "Nostr Doge",
    ticker: "NDOGE",
    description: "Such protocol. Very decentralized. Many relays. Wow.",
    image: "",
    creator: "npub1dogemaster",
    createdAt: NOW - 3600,
    marketCap: 156_700,
    supply: 1_000_000,
    replies: 28,
    price: 0.19,
    change24h: 12.7,
    volume24h: 41_200,
    holders: 203,
    curveProgress: 44,
    creatorShort: "4DoG...mAst",
  },
  {
    id: "mock-6",
    name: "21M Club",
    ticker: "21M",
    description: "Only 21 million sats will ever be locked in this token. Hard money meets memes.",
    image: "",
    creator: "npub1club21m",
    createdAt: NOW - 7200,
    marketCap: 89_300,
    supply: 1_000_000,
    replies: 19,
    price: 0.11,
    change24h: -2.1,
    volume24h: 18_900,
    holders: 144,
    curveProgress: 31,
    creatorShort: "6ClB...21mM",
  },
  {
    id: "mock-7",
    name: "RuneStone",
    ticker: "RUNE",
    description: "Ancient Bitcoin runes carved into the Ark. Immutable. Eternal.",
    image: "",
    creator: "npub1runecarver",
    createdAt: NOW - 14400,
    marketCap: 312_400,
    supply: 1_000_000,
    replies: 56,
    price: 0.38,
    change24h: 67.9,
    volume24h: 95_600,
    holders: 421,
    curveProgress: 71,
    creatorShort: "1RuN...cRvR",
  },
  {
    id: "mock-8",
    name: "GigaChad BTC",
    ticker: "GIGA",
    description: "For the gigachads who buy every dip. Diamond hands only.",
    image: "",
    creator: "npub1gigachad",
    createdAt: NOW - 600,
    marketCap: 78_100,
    supply: 1_000_000,
    replies: 22,
    price: 0.09,
    change24h: 234.8,
    volume24h: 67_300,
    holders: 98,
    curveProgress: 22,
    creatorShort: "8GiG...cHaD",
  },
  {
    id: "mock-9",
    name: "Zap Energy",
    ticker: "ZAP",
    description: "Powered by lightning zaps. Every zap increases the bonding curve. Pure energy.",
    image: "",
    creator: "npub1zapenergy",
    createdAt: NOW - 900,
    marketCap: 145_200,
    supply: 1_000_000,
    replies: 31,
    price: 0.18,
    change24h: 56.4,
    volume24h: 52_100,
    holders: 176,
    curveProgress: 41,
    creatorShort: "3ZaP...nRgY",
  },
  {
    id: "mock-10",
    name: "Honey Badger",
    ticker: "HBDG",
    description: "Honey badger don't care. Honey badger don't give a... It just runs on Ark.",
    image: "",
    creator: "npub1honeybadger",
    createdAt: NOW - 28800,
    marketCap: 467_800,
    supply: 1_000_000,
    replies: 73,
    price: 0.54,
    change24h: 5.1,
    volume24h: 83_400,
    holders: 489,
    curveProgress: 78,
    creatorShort: "0HnY...bDgR",
  },
  {
    id: "mock-11",
    name: "Block Party",
    ticker: "BLOK",
    description: "Every block is a party when you hold BLOK. Celebrating Bitcoin blocks since 2025.",
    image: "",
    creator: "npub1blockparty",
    createdAt: NOW - 50,
    marketCap: 12_400,
    supply: 1_000_000,
    replies: 4,
    price: 0.01,
    change24h: 0,
    volume24h: 12_400,
    holders: 23,
    curveProgress: 4,
    creatorShort: "5BLK...pRtY",
  },
  {
    id: "mock-12",
    name: "Number Go Up",
    ticker: "NGU",
    description: "The technology is simple. Number. Go. Up.",
    image: "",
    creator: "npub1ngutech",
    createdAt: NOW - 5400,
    marketCap: 223_600,
    supply: 1_000_000,
    replies: 41,
    price: 0.31,
    change24h: 18.9,
    volume24h: 71_800,
    holders: 267,
    curveProgress: 58,
    creatorShort: "7NgU...tEcH",
  },
];

